version: 1
policy:
  default:
    min: 80
  domains:
    - name: cmd
      match:
        - "./cmd/coverctl/..."
      min: 0  # Entry point, minimal logic
    - name: root
      match:
        - "./"
      min: 60
    - name: cli
      match:
        - "./internal/cli/..."
      min: 65
    - name: application
      match:
        - "./internal/application/..."
      min: 40
    - name: domain
      match:
        - "./internal/domain/..."
    - name: autodetect
      match:
        - "./internal/infrastructure/autodetect/..."
    - name: config
      match:
        - "./internal/infrastructure/config/..."
    - name: coverprofile
      match:
        - "./internal/infrastructure/coverprofile/..."
    - name: gotool
      match:
        - "./internal/infrastructure/gotool/..."
    - name: report
      match:
        - "./internal/infrastructure/report/..."
      min: 65
    - name: annotations
      match:
        - "./internal/infrastructure/annotations/..."
    - name: diff
      match:
        - "./internal/infrastructure/diff/..."
    - name: wizard
      match:
        - "./internal/infrastructure/wizard/..."
