version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - ineffassign
    - misspell
  settings:
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports
