version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - ineffassign
    - misspell

formatters:
  enable:
    - gofmt
    - goimports

settings:
  misspell:
    locale: US
