# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: coverctl

before:
  hooks:
    - go mod tidy

builds:
  - id: coverctl
    main: .
    binary: coverctl-{{ .Os }}-{{ .Arch }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/felixgeelhaar/coverctl/internal/cli.Version={{.Version}}
      - -X github.com/felixgeelhaar/coverctl/internal/cli.Commit={{.ShortCommit}}
      - -X github.com/felixgeelhaar/coverctl/internal/cli.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .Binary }}"

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

# Homebrew tap is updated via custom script (scripts/update-homebrew-tap.sh)
# to support both macOS and Linux via Linuxbrew

release:
  github:
    owner: felixgeelhaar
    name: coverctl
  draft: false
  prerelease: auto
  name_template: "Release {{.Tag}}"
